name: Build

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"
  pull_request:

jobs:
  build: // сборка, тесты
  release:
    name: Release
    runs-on: self-hosted
    container: ghcr.io/sitkoru/actions-container
    needs: [build]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Semantic Release
        uses: sitkoru/semantic-release-action@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
